# SPDX-License-Identifier: GPL-3.0-or-later

onchange-in += _headers

headers-y := $(pubdir)/_headers

distclean += $(headers-y)
deploy-ready-y += $(headers-y)

$(headers-y): $(pubdir)/%: %
	mkdir -p $(@D)
	$(m4) $< >$@
