# SPDX-License-Identifier: GPL-3.0-or-later

onchange-src += index.jsx page/*.jsx

page-src := index.jsx $(wildcard page/*.jsx)
page-m4 := $(addprefix $(m4dir)/,$(page-src))

clean += $(page-m4)

$(m4dir)/page/search_parser.js: parser/search.y parser/search.l
	$(jison) -o $@1 $^
	sed s/substr/[[substr]]/g $@1 >$@

$(page-m4): $(lib-helper) $(images_asmap)

$(m4dir)/page/credit.jsx: $(fonts_asmap) $(notice_map) $(license_map)

$(m4dir)/page/search.jsx: %.jsx: %_parser.js
