# SPDX-License-Identifier: GPL-3.0-or-later

onchange-src += LICENSES/*

license-src := $(wildcard LICENSES/*)
license-y := $(addprefix $(pubdir)/,$(license-src))
license_map := $(objtree)/license_map.m4

clean += $(license_map)
distclean += $(license-y)

$(license-y): $(pubdir)/%: %
	mkdir -p $(@D)
	cp $< $@

$(license_map): $(license-y)
	printf '/%s\n' $^ | sed s,/$(pubdir),, | $(map-license) >$@
