# SPDX-License-Identifier: GPL-3.0-or-later

onchange-src += lib/**/*

lib-src := $(shell find lib -type f)
lib-helper := $(wildcard lib/*.m4)
lib-m4 := $(addprefix $(m4dir)/,$(lib-src))

clean += $(lib-m4)

$(lib-m4): $(images_asmap) $(lib-helper)
