# SPDX-License-Identifier: GPL-3.0-or-later

onchange-src += index.jsx page/*.jsx

page-src := index.jsx $(wildcard page/*.jsx)
page-m4 := $(addprefix $(m4dir)/,$(page-src))

clean += $(page-m4)

$(page-m4): $(lib-helper) $(images_asmap)

$(m4dir)/page/credit.jsx: $(fonts_asmap) $(notice_map) $(license_map)
