# SPDX-License-Identifier: GPL-3.0-or-later

onchange-src += fonts/**/*

font-src := $(shell find fonts -type f)
font-y := $(addsuffix .stamp,$(addprefix $(pubdir)/,$(font-src)))

fonts_asmap := $(objtree)/fonts_asmap.m4
fonts_asmap_sed := $(objtree)/fonts_asmap.sed

clean += $(fonts_asmap) $(fonts_asmap_sed)
distclean += $(addsuffix *,$(basename $(basename $(font-y))))

$(fonts_asmap_sed):
	mkdir -p $(@D)
	printf '%s\n' s,^/fonts,FONTS, >$@

$(fonts_asmap): $(font-y)
